version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    assignees:
      - "ezio-melotti"
    groups:
      pip:
        patterns:
          - "*"
