name: Release_$(SourceTag)_$(Date:yyyyMMdd)$(Rev:.rr)

parameters:
- name: GitRemote
  displayName: "Git remote"
  type: string
  default: python
  values:
  - 'python'
  - 'hugovk'
  - 'Yhg1s'
  - 'pablogsal'
  - 'ambv'
  - 'zooba'
  - '(Other)'
- name: GitRemote_Other
  displayName: "If Other, specify Git remote"
  type: string
  default: 'python'
- name: SourceTag
  displayName: "Git tag"
  type: string
  default: main
- name: SourceCommit
  displayName: "Git commit ('empty' to disable commit SHA check)"
  type: string
  default: 'empty'
- name: DoPublish
  displayName: "Publish release"
  type: boolean
  default: false
- name: SigningCertificate
  displayName: "Code signing certificate"
  type: string
  default: 'PythonSoftwareFoundation'
  values:
  - 'PythonSoftwareFoundation'
  - 'TestSign'
  - 'Unsigned'
- name: SigningDescription
  displayName: "Signature description"
  type: string
  default: 'Built: $(Build.BuildNumber)'
- name: DoGPG
  displayName: "Include GPG signatures (3.13 and earlier)"
  type: boolean
  default: false
- name: DoFreethreaded
  displayName: "Include free-threaded builds (3.13 and later)"
  type: boolean
  default: true
- name: DoARM64
  displayName: "Publish ARM64 build (3.11 and later)"
  type: boolean
  default: true
- name: DoPGO
  displayName: "Run PGO"
  type: boolean
  default: true
- name: DoPGOARM64
  displayName: "Run ARM64 PGO (requires custom VM)"
  type: boolean
  default: true
- name: DoLayout
  displayName: "Produce full layout artifact"
  type: boolean
  default: true
- name: DoMSIX
  displayName: "Produce Store packages"
  type: boolean
  default: true
- name: DoNuget
  displayName: "Produce Nuget packages"
  type: boolean
  default: true
- name: DoEmbed
  displayName: "Produce embeddable package"
  type: boolean
  default: true
- name: DoMSI
  displayName: "Produce EXE/MSI installer"
  type: boolean
  default: true
- name: DoPyManager
  displayName: "Produce PyManager package"
  type: boolean
  default: true
- name: BuildToPublish
  displayName: "Build number to publish (0 to skip)"
  type: number
  default: '0'
- name: BuildToRepackage
  displayName: "Build number to repackage and publish (0 to skip)"
  type: number
  default: '0'
- name: SignNuget
  displayName: "Enable Nuget signing (not recommended right now)"
  type: boolean
  default: false

variables:
  ${{ if ne(parameters.GitRemote, '(Other)') }}:
    GitRemote: ${{ parameters.GitRemote }}
  ${{ else }}:
    GitRemote: ${{ parameters.GitRemote_Other }}
  SourceTag: ${{ parameters.SourceTag }}
  ${{ if ne(parameters.SourceCommit, 'empty') }}:
    SourceCommit: ${{ parameters.SourceCommit }}
  ${{ if ne(parameters.SigningCertificate, 'Unsigned') }}:
    SigningCertificate: ${{ parameters.SigningCertificate }}
  SigningDescription: ${{ parameters.SigningDescription }}
  IsRealSigned: ${{ eq(parameters.SigningCertificate, 'PythonSoftwareFoundation') }}
  PublishARM64: ${{ parameters.DoARM64 }}
  ${{ if ne(parameters.BuildToPublish, '0') }}:
    BuildToPublish: build_to_publish
  ${{ else }}:
    BuildToPublish: current
  ${{ if ne(parameters.BuildToRepackage, '0') }}:
    BuildToPackage: build_to_package
  ${{ else }}:
    BuildToPackage: current
# QUEUE TIME VARIABLES
#  PyDotOrgUsername: ''
#  PyDotOrgServer: ''

resources:
  pipelines:
  - ${{ if ne(parameters.BuildToPublish, '0') }}:
    - pipeline: build_to_publish
      source: $(Build.DefinitionName)
      version: ${{ parameters.BuildToPublish }}
  - ${{ if ne(parameters.BuildToRepackage, '0') }}:
    - pipeline: build_to_package
      source: $(Build.DefinitionName)
      version: ${{ parameters.BuildToRepackage }}

trigger: none
pr: none

stages:
- ${{ if and(eq(parameters.BuildToPublish, '0'), eq(parameters.BuildToRepackage, '0')) }}:
  - stage: Build
    displayName: Build binaries
    jobs:
    - template: stage-build.yml
      parameters:
        DoFreethreaded: ${{ parameters.DoFreethreaded }}
        DoPGO: ${{ parameters.DoPGO }}
        DoPGOARM64: ${{ parameters.DoPGOARM64 }}

  - stage: Sign
    displayName: Sign binaries
    dependsOn: Build
    jobs:
    - template: stage-sign.yml
      parameters:
        SigningCertificate: ${{ parameters.SigningCertificate }}
        DoFreethreaded: ${{ parameters.DoFreethreaded }}

- ${{ if eq(parameters.BuildToPublish, '0') }}:
  - stage: Layout
    ${{ if eq(parameters.BuildToRepackage, '0') }}:
      displayName: Generate layouts
      dependsOn: Sign
    ${{ else }}:
      displayName: Generate layouts from build ${{ parameters.BuildToRepackage }}
      dependsOn: []
    jobs:
    - template: stage-layout-full.yml
      parameters:
        ARM64TclTk: ${{ parameters.ARM64TclTk }}
        DoFreethreaded: ${{ parameters.DoFreethreaded }}
    - ${{ if eq(parameters.DoEmbed, 'true') }}:
      - template: stage-layout-embed.yml
    - ${{ if eq(parameters.DoNuget, 'true') }}:
      - template: stage-layout-nuget.yml
        parameters:
          DoFreethreaded: ${{ parameters.DoFreethreaded }}
    - ${{ if eq(parameters.DoMSIX, 'true') }}:
      - template: stage-layout-msix.yml
    - ${{ if eq(parameters.DoPyManager, 'true') }}:
      - template: stage-layout-pymanager.yml
        parameters:
          DoFreethreaded: ${{ parameters.DoFreethreaded }}
          DoEmbed: ${{ parameters.DoEmbed }}
          ${{ if ne(parameters.BuildToRepackage, '0') }}:
            UseLayoutScriptFromBranch: main

  - stage: Pack
    dependsOn: Layout
    displayName: Pack
    jobs:
    - ${{ if eq(parameters.DoEmbed, 'true') }}:
      - template: stage-pack-embed.yml
    - ${{ if eq(parameters.DoMSI, 'true') }}:
      - template: stage-msi.yml
        parameters:
          DoARM64: ${{ parameters.DoARM64}}
          DoFreethreaded: ${{ parameters.DoFreethreaded }}
    - ${{ if eq(parameters.DoMSIX, 'true') }}:
      - template: stage-pack-msix.yml
        parameters:
          ${{ if and(parameters.SigningCertificate, ne(parameters.SigningCertificate, 'Unsigned')) }}:
            SigningCertificate: ${{ parameters.SigningCertificate }}
    - ${{ if eq(parameters.DoNuget, 'true') }}:
      - template: stage-pack-nuget.yml
        parameters:
          ${{ if eq(parameters.SignNuget, 'true') }}:
            ${{ if and(parameters.SigningCertificate, ne(parameters.SigningCertificate, 'Unsigned')) }}:
              SigningCertificate: ${{ parameters.SigningCertificate }}
          DoFreethreaded: ${{ parameters.DoFreethreaded }}

  - stage: Test
    dependsOn: Pack
    jobs:
    - ${{ if eq(parameters.DoEmbed, 'true') }}:
      - template: stage-test-embed.yml
    - ${{ if eq(parameters.DoMSI, 'true') }}:
      - template: stage-test-msi.yml
        parameters:
          DoFreethreaded: ${{ parameters.DoFreethreaded }}
    - ${{ if eq(parameters.DoNuget, 'true') }}:
      - template: stage-test-nuget.yml
        parameters:
          DoFreethreaded: ${{ parameters.DoFreethreaded }}
    - ${{ if eq(parameters.DoPyManager, 'true') }}:
      - template: stage-test-pymanager.yml
        parameters:
          DoEmbed: ${{ parameters.DoEmbed }}
          DoFreethreaded: ${{ parameters.DoFreethreaded }}

- ${{ if eq(parameters.DoPublish, 'true') }}:
  - stage: Publish
    displayName: Publish
    dependsOn:
    - ${{ if eq(parameters.BuildToPublish, '0') }}:
      - Test
    jobs:
    - ${{ if eq(parameters.DoPyManager, 'true') }}:
      - template: stage-publish-pymanager.yml
        parameters:
          DoEmbed: ${{ parameters.DoEmbed }}
          DoFreethreaded: ${{ parameters.DoFreethreaded }}
    - ${{ if eq(parameters.DoMSI, 'true') }}:
      - template: stage-publish-pythonorg.yml
        parameters:
          DoEmbed: ${{ parameters.DoEmbed }}
          IncludeGPG: ${{ parameters.DoGPG }}
    - ${{ if eq(parameters.DoNuget, 'true') }}:
      - template: stage-publish-nugetorg.yml
