parameters:
- name: SourceTag
  displayName: 'OpenSSL Source Tag'
  type: string
- name: SigningCertificate
  displayName: "Code signing certificate"
  type: string
  default: 'PythonSoftwareFoundation'
  values:
  - 'PythonSoftwareFoundation'
  - 'TestSign'
  - 'Unsigned'
- name: SourcesRepo
  displayName: 'Sources Repository'
  type: string
  default: 'https://github.com/python/cpython-source-deps'
- name: CustomBuildVM
  displayName: 'Custom build VM'
  type: boolean
  default: false
- name: VCVarsOptions
  displayName: 'vcvarsall.bat options'
  type: string
  default: '(none)'
- name: IncludeX86
  displayName: 'Include x86'
  type: boolean
  default: true
- name: IncludeX64
  displayName: 'Include x64'
  type: boolean
  default: true
- name: IncludeARM64
  displayName: 'Include ARM64'
  type: boolean
  default: true


name: ${{ parameters.SourceTag }}_$(Date:yyyyMMdd)$(Rev:.rr)


variables:
- ${{ if eq(parameters.SigningCertificate, 'PythonSoftwareFoundation') }}:
  - group: CPythonSign
- ${{ if eq(parameters.SigningCertificate, 'TestSign') }}:
  - group: CPythonTestSign
- name: IntDir
  value: '$(Build.BinariesDirectory)'
- name: OutDir
  value: '$(Build.ArtifactStagingDirectory)'
- name: SigningDescription
  value: 'OpenSSL for Python (${{ parameters.SourceTag }})'


jobs:
- job: Build_SSL
  displayName: OpenSSL
  pool:
    ${{ if eq(parameters.CustomBuildVM, 'true') }}:
      name: 'Windows Release'
    ${{ else }}:
      vmImage: windows-latest

  strategy:
    matrix:
      ${{ if eq(parameters.IncludeX86, 'true') }}:
        win32:
          Platform: 'win32'
          VCPlatform: 'amd64_x86'
          OpenSSLPlatform: 'VC-WIN32 no-asm'
      ${{ if eq(parameters.IncludeX64, 'true') }}:
        amd64:
          Platform: 'amd64'
          VCPlatform: 'amd64'
          OpenSSLPlatform: 'VC-WIN64A-masm'
      ${{ if eq(parameters.IncludeARM64, 'true') }}:
        arm64:
          Platform: 'arm64'
          VCPlatform: 'amd64_arm64'
          OpenSSLPlatform: 'VC-WIN64-ARM'

  workspace:
    clean: all

  steps:
    - checkout: none

    - template: ./find-tools.yml

    - powershell: |
        git clone ${{ parameters.SourcesRepo }} -b ${{ parameters.SourceTag }} --depth 1 .
      displayName: 'Check out OpenSSL sources'

    - script: |
        call "$(vcvarsall)" $(VCPlatform) %EXTRA_OPTS%
        perl "$(Build.SourcesDirectory)\Configure" $(OpenSSLPlatform) no-uplink
        nmake
      workingDirectory: '$(IntDir)'
      displayName: 'Build OpenSSL'
      env:
        ${{ if ne(parameters.VCVarsOptions, '(none)') }}:
          EXTRA_OPTS: ${{ parameters.VCVarsOptions }}

    - ${{ if ne(parameters.SigningCertificate, 'Unsigned') }}:
      - template: sign-files.yml
        parameters:
          Include: 'lib*.dll'
          WorkingDir: $(IntDir)
          SigningCertificate: ${{ parameters.SigningCertificate }}

    - task: CopyFiles@2
      displayName: 'Copy built libraries for upload'
      inputs:
        SourceFolder: '$(IntDir)'
        Contents: |
          lib*.dll
          lib*.pdb
          lib*.lib
          include\openssl\*.h
        TargetFolder: '$(OutDir)'

    - task: CopyFiles@2
      displayName: 'Copy header files for upload'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
          include\openssl\*
        TargetFolder: '$(OutDir)'

    - task: CopyFiles@2
      displayName: 'Copy applink files for upload'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)\ms'
        Contents: applink.c
        TargetFolder: '$(OutDir)\include'

    - task: CopyFiles@2
      displayName: 'Copy LICENSE for upload'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
          LICENSE
          LICENSE.txt
        TargetFolder: '$(OutDir)'

    - publish: '$(OutDir)'
      artifact: '$(Platform)'
      displayName: 'Publishing $(Platform)'
