parameters:
  BuildToPublish: ''
  HashAlgorithms: ['SHA256']

jobs:
- job: Publish_PyManager
  displayName: Publish PyManager packages to python.org
  condition: and(succeeded(), ne(variables['SkipPythonOrgPublish'], 'true'))

  pool:
    vmImage: windows-2022

  variables:
  - group: PythonOrgPublish

  workspace:
    clean: all

  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.10 or later'
    inputs:
      versionSpec: '>=3.10'

  - ${{ if parameters.BuildToPublish }}:
    - ${{ each Name in variables.artifacts }}:
      - task: DownloadPipelineArtifact@1
        displayName: 'Download artifact from ${{ parameters.BuildToPublish}}: pymanager_${{ Name }}'
        inputs:
          artifactName: pymanager_${{ Name }}
          targetPath: $(Pipeline.Workspace)
          buildType: specific
          project: $(System.TeamProject)
          pipeline: $(Build.DefinitionName)
          buildVersionToDownload: specific
          buildId: ${{ parameters.BuildToPublish }}

  - ${{ else }}:
    - ${{ each Name in variables.artifacts }}:
      - download: current
        artifact: pymanager_${{ Name }}
        displayName: 'Download artifact: pymanager_${{ Name }}'


  - task: DownloadSecureFile@1
    name: sshkey
    inputs:
      secureFile: pydotorg-ssh.ppk
    displayName: 'Download PuTTY key'

  - powershell: |
      "Uploading following packages:"
      dir "*\__install__.json"
      python merge-and-upload.py 
    workingDirectory: $(Pipeline.Workspace)
    displayName: 'Upload ZIPs'
    env:
      INDEX_URL: '$(PyDotOrgUrlPrefix)python/__index_windows__.json'
      INDEX_FILE: '$(Build.ArtifactStagingDirectory)\index\__index__.json'
      UPLOAD_URL_PREFIX: $(PyDotOrgUrlPrefix)
      UPLOAD_PATH_PREFIX: $(PyDotOrgUploadPathPrefix)
      UPLOAD_HOST: $(PyDotOrgServer)
      UPLOAD_HOST_KEY: $(PyDotOrgHostKey)
      UPLOAD_USER: $(PyDotOrgUsername)
      UPLOAD_KEYFILE: $(sshkey.secureFilePath)

  - ${{ each alg in parameters.HashAlgorithms }}:
    - powershell: |
        $files = (dir "*\__install__.json").Directory | %{ dir -File "$_\*.zip" }
        $hashes = $files  | `
            Sort-Object Name | `
            Format-Table Name, @{
              Label="${{ alg }}";
              Expression={(Get-FileHash $_ -Algorithm ${{ alg }}).Hash}
            }, Length -AutoSize | `
            Out-String -Width 4096
        $d = mkdir "$(Build.ArtifactStagingDirectory)\hashes" -Force
        $hashes | Out-File "$d\hashes.txt" -Encoding ascii -Append
        $hashes
      workingDirectory: $(Pipeline.Workspace)
      displayName: 'Generate hashes (${{ alg }})'

  - publish: '$(Build.ArtifactStagingDirectory)\index'
    artifact: pymanager_index

  - publish: '$(Build.ArtifactStagingDirectory)\hashes'
    artifact: hashes
    displayName: 'Publish Artifact: hashes'
