parameters:
  pool: windows-latest
  BuildToPackage: current
  DoFreethreaded: false
  SigningCertificate: ''

jobs:
- job: Make_Nuget_Layout
  displayName: Make Nuget layout

  pool:
    ${{ if containsValue(parameters.pool, 'name') }}:
      ${{ each p in parameters.pool }}:
        ${{ p.key }}: ${{ p.value }}
    ${{ else }}:
      vmImage: ${{ parameters.pool }}

  workspace:
    clean: all

  variables:
    PYTHONHOME: $(Build.SourcesDirectory)

  strategy:
    matrix:
      win32:
        Name: win32
        Arch: win32
        ExtraOptions: ''
      amd64:
        Name: amd64
        Arch: amd64
        ExtraOptions: ''
      arm64:
        Name: arm64
        Arch: arm64
        HostArch: amd64
        ExtraOptions: ''
      ${{ if eq(parameters.DoFreethreaded, 'true') }}:
        win32_t:
          Name: win32_t
          Arch: win32
          HostArch: win32
          ExtraOptions: --include-freethreaded
        amd64_t:
          Name: amd64_t
          Arch: amd64
          HostArch: amd64
          ExtraOptions: --include-freethreaded
        arm64_t:
          Name: arm64_t
          Arch: arm64
          HostArch: amd64
          ExtraOptions: --include-freethreaded

  steps:
  - template: ./checkout.yml

  - task: DownloadPipelineArtifact@2
    displayName: 'Download artifact: bin_$(Name)'
    inputs:
      ${{ if eq(parameters.BuildToPackage, 'current') }}:
        buildType: current
      ${{ else }}:
        buildType: specific
        buildVersionToDownload: specific
        project: $(resources.pipeline.build_to_package.projectId)
        pipeline: $(resources.pipeline.build_to_package.pipelineId)
        runId: $(resources.pipeline.build_to_package.runID)
      artifact: bin_$(Name)
      targetPath: $(Pipeline.Workspace)\bin_$(Name)

  - ${{ if parameters.SigningCertificate }}:
    - powershell: |
        copy $(Pipeline.Workspace)\bin_$(Name)\Activate.ps1 Lib\venv\scripts\common\Activate.ps1 -Force
      displayName: 'Copy signed files into sources'

  - template: ./layout-command.yml
    parameters:
      BuildToPackage: ${{ parameters.BuildToPackage }}

  - powershell: |
      $(LayoutCmd) --copy "$(Build.ArtifactStagingDirectory)\nuget" --preset-nuget $(ExtraOptions)
    displayName: 'Generate nuget layout'

  - publish: '$(Build.ArtifactStagingDirectory)\nuget'
    artifact: layout_nuget_$(Name)
    displayName: 'Publish Artifact: layout_nuget_$(Name)'
