jobs:
- job: SBOM_Files
  displayName: Create SBOMs for Python binaries

  pool:
    vmImage: windows-2022

  workspace:
    clean: all

  strategy:
    matrix:
      win32:
        Name: win32
      amd64:
        Name: amd64
      arm64:
        Name: arm64

  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.6 or later'
    inputs:
      versionSpec: '>=3.6'

  - template: ./checkout.yml

  - task: DownloadPipelineArtifact@1
    displayName: 'Download artifact: bin_$(Name)'
    inputs:
      artifactName: bin_$(Name)
      targetPath: $(Build.BinariesDirectory)\bin

  - powershell: >
      python
      "$(Build.SourcesDirectory)\sbom.py"
      "--cpython-source-dir=$(Build.SourcesDirectory)"
      (gci msi\*\python-*.exe)
    workingDirectory: $(Build.BinariesDirectory)
    displayName: 'Create SBOMs for binaries'

  - task: CopyFiles@2
    displayName: 'Layout Artifact: sbom'
    inputs:
      sourceFolder: $(Build.BinariesDirectory)\bin
      targetFolder: $(Build.ArtifactStagingDirectory)\sbom
      flatten: true
      contents: |
        **\*.spdx.json

  - publish: '$(Build.ArtifactStagingDirectory)\sbom'
    artifact: sbom
    displayName: 'Publish artifact: sbom'
