parameters:
  DoFreethreaded: false
  SigningCertificate: ''

jobs:
- job: Pack_Nuget
  displayName: Pack Nuget bundles
  condition: and(succeeded(), eq(variables['DoNuget'], 'true'))

  pool:
    vmImage: windows-2022

  workspace:
    clean: all

  strategy:
    matrix:
      amd64:
        Name: amd64
      win32:
        Name: win32
      arm64:
        Name: arm64
      ${{ if eq(parameters.DoFreethreaded, 'true') }}:
        amd64_t:
          Name: amd64_t
        win32_t:
          Name: win32_t
        arm64_t:
          Name: arm64_t

  variables:
  - ${{ if eq(parameters.SigningCertificate, 'PythonSoftwareFoundation') }}:
    - group: CPythonSign
  - ${{ if eq(parameters.SigningCertificate, 'TestSign') }}:
    - group: CPythonTestSign

  steps:
  - checkout: none

  - download: current
    artifact: layout_nuget_$(Name)
    displayName: 'Download artifact: layout_nuget_$(Name)'

  - task: NugetToolInstaller@0
    displayName: 'Install Nuget'
    inputs:
      versionSpec: '>=5.0'

  - powershell: >
      nuget pack
      "$(Pipeline.Workspace)\layout_nuget_$(Name)\python.nuspec"
      -OutputDirectory $(Build.ArtifactStagingDirectory)
      -NoPackageAnalysis
      -NonInteractive
    condition: and(succeeded(), not(variables['OverrideNugetVersion']))
    displayName: 'Create nuget package'

  - powershell: >
      nuget pack
      "$(Pipeline.Workspace)\layout_nuget_$(Name)\python.nuspec"
      -OutputDirectory $(Build.ArtifactStagingDirectory)
      -NoPackageAnalysis
      -NonInteractive
      -Version "$(OverrideNugetVersion)"
    condition: and(succeeded(), variables['OverrideNugetVersion'])
    displayName: 'Create nuget package'

  - template: sign-files.yml
    parameters:
      Include: '*.nupkg'
      # Additional filter to avoid recursively signing package contents
      Filter: '*.nupkg'
      WorkingDir: $(Build.ArtifactStagingDirectory)
      SigningCertificate: ${{ parameters.SigningCertificate }}
      # Nuget signing is not supported by our test certificate, so ignore errors
      ${{ if eq(parameters.SigningCertificate, 'TestSign') }}:
        ContinueOnError: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: nuget'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: nuget
