parameters:
  pool: windows-latest
  BuildToPackage: current
  SigningCertificate: ''

jobs:
- job: Make_MSIX_Layout
  displayName: Make MSIX layout

  pool:
    ${{ if containsValue(parameters.pool, 'name') }}:
      ${{ each p in parameters.pool }}:
        ${{ p.key }}: ${{ p.value }}
    ${{ else }}:
      vmImage: ${{ parameters.pool }}

  workspace:
    clean: all

  variables:
    PYTHONHOME: $(Build.SourcesDirectory)

  strategy:
    matrix:
      #win32:
      #  Name: win32
      #  TclLibrary: tcltk_lib_win32
      #  ExtraOptions: --precompile
      amd64:
        Name: amd64
        Arch: amd64
        TclLibrary: tcltk_lib_amd64
        ExtraOptions: --precompile
      arm64:
        Name: arm64
        Arch: arm64
        HostArch: amd64
        TclLibrary: tcltk_lib_arm64
        ExtraOptions: --precompile

  steps:
  - template: ./checkout.yml

  - task: DownloadPipelineArtifact@2
    displayName: 'Download artifact: bin_$(Name)'
    inputs:
      ${{ if eq(parameters.BuildToPackage, 'current') }}:
        buildType: current
      ${{ else }}:
        buildType: specific
        buildVersionToDownload: specific
        project: $(resources.pipeline.build_to_package.projectId)
        pipeline: $(resources.pipeline.build_to_package.pipelineId)
        runId: $(resources.pipeline.build_to_package.runID)
      artifact: bin_$(Name)
      targetPath: $(Pipeline.Workspace)\bin_$(Name)

  - task: DownloadPipelineArtifact@2
    displayName: 'Download artifact: $(TclLibrary)'
    condition: and(succeeded(), variables['TclLibrary'])
    inputs:
      ${{ if eq(parameters.BuildToPackage, 'current') }}:
        buildType: current
      ${{ else }}:
        buildType: specific
        buildVersionToDownload: specific
        project: $(resources.pipeline.build_to_package.projectId)
        pipeline: $(resources.pipeline.build_to_package.pipelineId)
        runId: $(resources.pipeline.build_to_package.runID)
      artifact: $(TclLibrary)
      targetPath: $(Pipeline.Workspace)\$(TclLibrary)

  - powershell: |
      Write-Host "##vso[task.setvariable variable=TCL_LIBRARY]$(Pipeline.Workspace)\$(TclLibrary)\tcl8"
    displayName: 'Update TCL_LIBRARY'
    condition: and(succeeded(), variables['TclLibrary'])

  - ${{ if parameters.SigningCertificate }}:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download artifact: cert'
      inputs:
        ${{ if eq(parameters.BuildToPackage, 'current') }}:
          buildType: current
        ${{ else }}:
          buildType: specific
          buildVersionToDownload: specific
          project: $(resources.pipeline.build_to_package.projectId)
          pipeline: $(resources.pipeline.build_to_package.pipelineId)
          runId: $(resources.pipeline.build_to_package.runID)
        artifact: cert
        targetPath: $(Pipeline.Workspace)\cert

    - powershell: |
        copy "$(Pipeline.Workspace)\bin_$(Name)\Activate.ps1" Lib\venv\scripts\common\Activate.ps1 -Force
      displayName: 'Copy signed files into sources'

  - template: ./layout-command.yml
    parameters:
      BuildToPackage: ${{ parameters.BuildToPackage }}

  - powershell: |
     Remove-Item "$(Build.ArtifactStagingDirectory)\appx-store" -Recurse -Force -EA 0
      $(LayoutCmd) --copy "$(Build.ArtifactStagingDirectory)\appx-store" --preset-appx $(ExtraOptions)
    displayName: 'Generate store APPX layout'
    env:
      TCL_LIBRARY: $(TclLibrary)

  - ${{ if parameters.SigningCertificate }}:
    # The dotnet sign tool shouldn't need this, but we do because of the sccd file
    - powershell: |
        $info = (gc "$(Pipeline.Workspace)\cert\certinfo.json" | ConvertFrom-JSON)
        Write-Host "Side-loadable APPX must be signed with '$($info.Subject)'"
        Write-Host "##vso[task.setvariable variable=APPX_DATA_PUBLISHER]$($info.Subject)"
        Write-Host "##vso[task.setvariable variable=APPX_DATA_SHA256]$($info.SHA256)"
      displayName: 'Override signing parameters'

  - powershell: |
      Remove-Item "$(Build.ArtifactStagingDirectory)\appx" -Recurse -Force -EA 0
      $(LayoutCmd) --copy "$(Build.ArtifactStagingDirectory)\appx" --preset-appx --include-symbols --include-tests $(ExtraOptions)
    displayName: 'Generate sideloading APPX layout'
    env:
      TCL_LIBRARY: $(TclLibrary)

  - publish: '$(Build.ArtifactStagingDirectory)\appx-store'
    artifact: layout_appxstore_$(Name)
    displayName: 'Publish Artifact: layout_appxstore_$(Name)'

  - publish: '$(Build.ArtifactStagingDirectory)\appx'
    artifact: layout_appx_$(Name)
    displayName: 'Publish Artifact: layout_appx_$(Name)'
