parameters:
  DoPGO: false
  # DoPGOARM64 only applies if DoPGO is also true
  DoPGOARM64: true
  DoFreethreaded: false
  ToBeSigned: false

jobs:
- job: Build_Docs
  displayName: Docs build
  pool:
    vmImage: windows-2022

  workspace:
    clean: all

  steps:
  - template: ./checkout.yml

  - script: Doc\make.bat html
    displayName: 'Build HTML docs'
    env:
      BUILDDIR: $(Build.BinariesDirectory)\Doc

  - task: CopyFiles@2
    displayName: 'Assemble artifact: Doc'
    inputs:
      sourceFolder: $(Build.BinariesDirectory)\Doc
      targetFolder: $(Build.ArtifactStagingDirectory)\Doc
      contents: |
        html\**\*

  - publish: $(Build.ArtifactStagingDirectory)\Doc
    artifact: doc
    displayName: 'Publish artifact: doc'


- job: Build_Python
  displayName: Python build

  pool:
    vmImage: windows-2022

  workspace:
    clean: all

  strategy:
    matrix:
      win32:
        Name: win32
        Arch: win32
        Platform: x86
        Configuration: Release
        _HostPython: .\python
        ExtraOptions: ''
        ${{ if eq(parameters.ToBeSigned, 'true') }}:
          Artifact: unsigned_win32
        ${{ else }}:
          Artifact: bin_win32
      win32_d:
        Name: win32_d
        Arch: win32
        Platform: x86
        Configuration: Debug
        _HostPython: .\python
        ExtraOptions: ''
        Artifact: bin_win32_d
      ${{ if ne(parameters.DoPGO, 'true') }}:
        amd64:
          Name: amd64
          Arch: amd64
          Platform: x64
          Configuration: Release
          _HostPython: .\python
          ExtraOptions: ''
          ${{ if eq(parameters.ToBeSigned, 'true') }}:
            Artifact: unsigned_amd64
          ${{ else }}:
            Artifact: bin_amd64
      amd64_d:
        Name: amd64_d
        Arch: amd64
        Platform: x64
        Configuration: Debug
        _HostPython: .\python
        ExtraOptions: ''
        Artifact: bin_amd64_d
      ${{ if or(ne(parameters.DoPGO, 'true'), ne(parameters.DoPGOARM64, 'true')) }}:
        arm64:
          Name: arm64
          Arch: arm64
          Platform: ARM64
          Configuration: Release
          _HostPython: python
          ExtraOptions: ''
          ${{ if eq(parameters.ToBeSigned, 'true') }}:
            Artifact: unsigned_arm64
          ${{ else }}:
            Artifact: bin_arm64
      arm64_d:
        Name: arm64_d
        Arch: arm64
        Platform: ARM64
        Configuration: Debug
        _HostPython: python
        ExtraOptions: ''
        Artifact: bin_arm64_d
      ${{ if eq(parameters.DoFreethreaded, 'true') }}:
        win32_t:
          Name: win32_t
          Arch: win32
          Platform: x86
          Configuration: Release
          _HostPython: .\python
          ExtraOptions: --disable-gil
          ${{ if eq(parameters.ToBeSigned, 'true') }}:
            Artifact: unsigned_win32_t
          ${{ else }}:
            Artifact: bin_win32_t
        win32_td:
          Name: win32_td
          Arch: win32
          Platform: x86
          Configuration: Debug
          _HostPython: .\python
          ExtraOptions: --disable-gil
          Artifact: bin_win32_td
        ${{ if ne(parameters.DoPGO, 'true') }}:
          amd64_t:
            Name: amd64_t
            Arch: amd64
            Platform: x64
            Configuration: Release
            _HostPython: .\python
            ExtraOptions: --disable-gil
            ${{ if eq(parameters.ToBeSigned, 'true') }}:
              Artifact: unsigned_amd64_t
            ${{ else }}:
              Artifact: bin_amd64_t
        amd64_td:
          Name: amd64_td
          Arch: amd64
          Platform: x64
          Configuration: Debug
          _HostPython: .\python
          ExtraOptions: --disable-gil
          Artifact: bin_amd64_td
        ${{ if or(ne(parameters.DoPGO, 'true'), ne(parameters.DoPGOARM64, 'true')) }}:
          arm64_t:
            Name: arm64_t
            Arch: arm64
            Platform: ARM64
            Configuration: Release
            _HostPython: python
            ExtraOptions: --disable-gil
            ${{ if eq(parameters.ToBeSigned, 'true') }}:
              Artifact: unsigned_arm64_t
            ${{ else }}:
              Artifact: bin_arm64_t
        arm64_td:
          Name: arm64_td
          Arch: arm64
          Platform: ARM64
          Configuration: Debug
          _HostPython: python
          ExtraOptions: --disable-gil
          Artifact: bin_arm64_td

  steps:
    - template: ./build-steps.yml


- ${{ if eq(parameters.DoPGO, 'true') }}:
  - job: Build_Python_PGO_Native
    displayName: Python PGO build

    pool:
      vmImage: windows-2022

    workspace:
      clean: all

    strategy:
      matrix:
        amd64:
          Name: amd64
          Arch: amd64
          Platform: x64
          _HostPython: .\python
          PythonExePattern: python.exe
          ExtraOptions: ''
          ${{ if eq(parameters.ToBeSigned, 'true') }}:
            Artifact: unsigned_amd64
          ${{ else }}:
            Artifact: bin_amd64
        ${{ if eq(parameters.DoFreethreaded, 'true') }}:
          amd64_t:
            Name: amd64_t
            Arch: amd64
            Platform: x64
            _HostPython: .\python
            PythonExePattern: python3*t.exe
            ExtraOptions: --disable-gil
            ${{ if eq(parameters.ToBeSigned, 'true') }}:
              Artifact: unsigned_amd64_t
            ${{ else }}:
              Artifact: bin_amd64_t

    steps:
      - template: ./build-steps-pgo.yml
        parameters:
          PGInstrument: true
          PGRun: true
          PGUpdate: true

  - ${{ if eq(parameters.DoPGOARM64, 'true') }}:
    - job: Build_Python_PGO_1
      displayName: Python PGO build

      pool:
        vmImage: windows-2022

      workspace:
        clean: all

      variables:
        Arch: arm64
        Platform: ARM64
        _HostPython: python

      strategy:
        matrix:
          arm64:
            Name: arm64
            PythonExePattern: python.exe
            ExtraOptions: ''
            ${{ if eq(parameters.ToBeSigned, 'true') }}:
              Artifact: unsigned_arm64
            ${{ else }}:
              Artifact: bin_arm64
          ${{ if eq(parameters.DoFreethreaded, 'true') }}:
            arm64_t:
              Name: arm64_t
              PythonExePattern: python3*t.exe
              ExtraOptions: --disable-gil
              ${{ if eq(parameters.ToBeSigned, 'true') }}:
                Artifact: unsigned_arm64_t
              ${{ else }}:
                Artifact: bin_arm64_t

      steps:
        - template: ./build-steps-pgo.yml
          parameters:
            PGInstrument: true

    - job: Build_Python_PGO_2
      displayName: Collect PGO profile
      dependsOn: Build_Python_PGO_1

      # Allow up to five hours for PGO run
      timeoutInMinutes: 300

      pool:
        name: 'Windows ARM64'

      workspace:
        clean: all

      variables:
        Arch: arm64
        Platform: ARM64

      strategy:
        matrix:
          arm64:
            Name: arm64
            PythonExePattern: python.exe
            ${{ if eq(parameters.ToBeSigned, 'true') }}:
              Artifact: unsigned_arm64
            ${{ else }}:
              Artifact: bin_arm64
          ${{ if eq(parameters.DoFreethreaded, 'true') }}:
            arm64_t:
              Name: arm64_t
              PythonExePattern: python3*t.exe
              ${{ if eq(parameters.ToBeSigned, 'true') }}:
                Artifact: unsigned_arm64_t
              ${{ else }}:
                Artifact: bin_arm64_t

      steps:
        - template: ./build-steps-pgo.yml
          parameters:
            PGRun: true

    - job: Build_Python_PGO_3
      displayName: Merge PGO profile
      dependsOn: Build_Python_PGO_2

      pool:
        vmImage: windows-2022

      workspace:
        clean: all

      variables:
        Arch: arm64
        Platform: ARM64
        _HostPython: python

      strategy:
        matrix:
          arm64:
            Name: arm64
            PythonExePattern: python.exe
            ExtraOptions: ''
            ${{ if eq(parameters.ToBeSigned, 'true') }}:
              Artifact: unsigned_arm64
            ${{ else }}:
              Artifact: bin_arm64
          ${{ if eq(parameters.DoFreethreaded, 'true') }}:
            arm64_t:
              Name: arm64_t
              PythonExePattern: python3*t.exe
              ExtraOptions: --disable-gil
              ${{ if eq(parameters.ToBeSigned, 'true') }}:
                Artifact: unsigned_arm64_t
              ${{ else }}:
                Artifact: bin_arm64_t

      steps:
        - template: ./build-steps-pgo.yml
          parameters:
            PGUpdate: true


- job: TclTk_Lib
  displayName: Publish Tcl/Tk Library

  pool:
    vmImage: windows-2022

  workspace:
    clean: all

  steps:
  - template: ./checkout.yml

  - script: PCbuild\get_externals.bat --no-openssl --no-libffi
    displayName: 'Get external dependencies'

  - task: MSBuild@1
    displayName: 'Copy Tcl/Tk lib for publish'
    inputs:
      solution: PCbuild\tcltk.props
      platform: x86
      msbuildArguments: /t:CopyTclTkLib /p:OutDir="$(Build.ArtifactStagingDirectory)\tcl_win32"

  - task: MSBuild@1
    displayName: 'Copy Tcl/Tk lib for publish'
    inputs:
      solution: PCbuild\tcltk.props
      platform: x64
      msbuildArguments: /t:CopyTclTkLib /p:OutDir="$(Build.ArtifactStagingDirectory)\tcl_amd64"

  - task: MSBuild@1
    displayName: 'Copy Tcl/Tk lib for publish'
    inputs:
      solution: PCbuild\tcltk.props
      platform: ARM64
      msbuildArguments: /t:CopyTclTkLib /p:OutDir="$(Build.ArtifactStagingDirectory)\tcl_arm64"

  - publish: '$(Build.ArtifactStagingDirectory)\tcl_win32'
    artifact: tcltk_lib_win32
    displayName: 'Publish artifact: tcltk_lib_win32'

  - publish: '$(Build.ArtifactStagingDirectory)\tcl_amd64'
    artifact: tcltk_lib_amd64
    displayName: 'Publish artifact: tcltk_lib_amd64'

  - publish: '$(Build.ArtifactStagingDirectory)\tcl_arm64'
    artifact: tcltk_lib_arm64
    displayName: 'Publish artifact: tcltk_lib_arm64'
