parameters:
  ARM64TclTk: true
  SigningCertificate: ''

jobs:
- ${{ if parameters.SigningCertificate }}:
  - job: Make_Signed_MSI
    displayName: Make signed MSI
  
    pool:
      vmImage: windows-2022
  
    variables:
    - group: CPythonSign
    - name: ReleaseUri
      value: http://www.python.org/{arch}
    - name: DownloadUrl
      value: https://www.python.org/ftp/python/{version}/{arch}{releasename}/{msi}
    - name: Py_OutDir
      value: $(Build.BinariesDirectory)
  
    workspace:
      clean: all
  
    steps:
    - template: msi-steps.yml
      parameters:
        ARM64TclTk: ${{ parameters.ARM64TclTk }}
        SigningCertificate: ${{ parameters.SigningCertificate }}


- ${{ else }}:
  - job: Make_MSI
    displayName: Make MSI
  
    pool:
      vmImage: windows-2022
  
    variables:
      ReleaseUri: http://www.python.org/{arch}
      DownloadUrl: https://www.python.org/ftp/python/{version}/{arch}{releasename}/{msi}
      Py_OutDir: $(Build.BinariesDirectory)
  
    workspace:
      clean: all
  
    steps:
    - template: msi-steps.yml
      parameters:
        ARM64TclTk: ${{ parameters.ARM64TclTk }}
