parameters:
  pool: windows-latest
  BuildToPackage: current
  DoARM64: true
  DoFreethreaded: false
  SigningCertificate: ''

jobs:
- job: Make_MSI
  displayName: Make MSI

  pool:
    ${{ if containsValue(parameters.pool, name) }}:
      ${{ each p in parameters.pool }}:
        ${{ p.key }}: ${{ p.value }}
    ${{ else }}:
      vmImage: ${{ parameters.pool }}

  variables:
  - ${{ if eq(parameters.SigningCertificate, 'PythonSoftwareFoundation') }}:
    - group: CPythonSign
  - ${{ if eq(parameters.SigningCertificate, 'TestSign') }}:
    - group: CPythonTestSign
  - name: ReleaseUri
    value: http://www.python.org/{arch}
  - name: DownloadUrl
    value: https://www.python.org/ftp/python/{version}/{arch}{releasename}/{msi}
  - name: Py_OutDir
    value: $(Build.BinariesDirectory)

  workspace:
    clean: all

  steps:
  - template: msi-steps.yml
    parameters:
      BuildToPackage: ${{ parameters.BuildToPackage }}
      DoFreethreaded: ${{ parameters.DoFreethreaded }}
      SigningCertificate: ${{ parameters.SigningCertificate }}
      Artifacts:
      - artifact: doc
        target: $(Build.SourcesDirectory)\Doc\build
      - artifact: bin_win32
        target: $(Build.BinariesDirectory)\win32
      - artifact: bin_win32_d
        target: $(Build.BinariesDirectory)\win32
      - artifact: tcltk_lib_win32
      - artifact: bin_amd64
        target: $(Build.BinariesDirectory)\amd64
      - artifact: bin_amd64_d
        target: $(Build.BinariesDirectory)\amd64
      - artifact: tcltk_lib_amd64
      - ${{ if eq(parameters.DoARM64, 'true') }}:
        - artifact: bin_arm64
          target: $(Build.BinariesDirectory)\arm64
        - artifact: bin_arm64_d
          target: $(Build.BinariesDirectory)\arm64
        - artifact: tcltk_lib_arm64
      # Freethreaded binaries copy into the same target directory, but files
      # are not overwritten.
      - ${{ if eq(parameters.DoFreethreaded, 'true') }}:
        - artifact: bin_win32_t
          target: $(Build.BinariesDirectory)\win32
        - artifact: bin_win32_td
          target: $(Build.BinariesDirectory)\win32
        - artifact: bin_amd64_t
          target: $(Build.BinariesDirectory)\amd64
        - artifact: bin_amd64_td
          target: $(Build.BinariesDirectory)\amd64
        - ${{ if eq(parameters.DoARM64, 'true') }}:
          - artifact: bin_arm64_t
            target: $(Build.BinariesDirectory)\arm64
          - artifact: bin_arm64_td
            target: $(Build.BinariesDirectory)\arm64
      Bundles:
      - bundle: win32
        Platform: x86
        PythonForBuild: $(Build.BinariesDirectory)\win32
        TclTkArtifact: tcltk_lib_win32
      - bundle: amd64
        Platform: x64
        PythonForBuild: $(Build.BinariesDirectory)\amd64
        TclTkArtifact: tcltk_lib_amd64
      - ${{ if eq(parameters.DoARM64, 'true') }}:
        - bundle: arm64
          Platform: ARM64
          PythonForBuild: $(Build.BinariesDirectory)\win32
          TclTkArtifact: tcltk_lib_arm64
