parameters:
  ARM64TclTk: true
  DoPGO: false
  # DoPGOARM64 only applies if DoPGO is also true
  DoPGOARM64: true

jobs:
- job: Build_Docs
  displayName: Docs build
  pool:
    vmImage: windows-2022

  workspace:
    clean: all

  steps:
  - template: ./checkout.yml

  - script: Doc\make.bat html
    displayName: 'Build HTML docs'
    env:
      BUILDDIR: $(Build.BinariesDirectory)\Doc

  - script: Doc\make.bat htmlhelp
    displayName: 'Build CHM docs'
    condition: and(succeeded(), eq(variables['DoCHM'], 'true'))
    env:
      BUILDDIR: $(Build.BinariesDirectory)\Doc

  - task: CopyFiles@2
    displayName: 'Assemble artifact: Doc'
    inputs:
      sourceFolder: $(Build.BinariesDirectory)\Doc
      targetFolder: $(Build.ArtifactStagingDirectory)\Doc
      contents: |
        html\**\*
        htmlhelp\*.chm

  - task: PublishPipelineArtifact@0
    displayName: 'Publish artifact: doc'
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)\Doc
      artifactName: doc


- job: Build_Python
  displayName: Python build

  pool:
    vmImage: windows-2022

  workspace:
    clean: all

  strategy:
    matrix:
      win32:
        Name: win32
        Arch: win32
        Platform: x86
        Configuration: Release
        _HostPython: .\python
      win32_d:
        Name: win32_d
        Arch: win32
        Platform: x86
        Configuration: Debug
        _HostPython: .\python
      ${{ if ne(parameters.DoPGO, 'true') }}:
        amd64:
          Name: amd64
          Arch: amd64
          Platform: x64
          Configuration: Release
          _HostPython: .\python
      amd64_d:
        Name: amd64_d
        Arch: amd64
        Platform: x64
        Configuration: Debug
        _HostPython: .\python
      ${{ if or(ne(parameters.DoPGO, 'true'), ne(parameters.DoPGOARM64, 'true')) }}:
        arm64:
          Name: arm64
          Arch: arm64
          Platform: ARM64
          Configuration: Release
          _HostPython: python
      arm64_d:
        Name: arm64_d
        Arch: arm64
        Platform: ARM64
        Configuration: Debug
        _HostPython: python

  steps:
    - template: ./build-steps.yml


- ${{ if eq(parameters.DoPGO, 'true') }}:
  - job: Build_Python_PGO_Native
    displayName: Python PGO build

    pool:
      vmImage: windows-2022

    workspace:
      clean: all

    strategy:
      matrix:
        amd64:
          Name: amd64
          Arch: amd64
          Platform: x64
          _HostPython: .\python

    steps:
      - template: ./build-steps-pgo.yml
        parameters:
          PGInstrument: true
          PGRun: true
          PGUpdate: true

  - ${{ if eq(parameters.DoPGOARM64, 'true') }}:
    - job: Build_Python_PGO_1
      displayName: Python PGO build

      pool:
        vmImage: windows-2022

      workspace:
        clean: all

      strategy:
        matrix:
          arm64:
            Name: arm64
            Arch: arm64
            Platform: ARM64
            _HostPython: python

      steps:
        - template: ./build-steps-pgo.yml
          parameters:
            PGInstrument: true

    - job: Build_Python_PGO_2
      displayName: Collect PGO profile
      dependsOn: Build_Python_PGO_1

      # Allow up to five hours for PGO run
      timeoutInMinutes: 300

      pool:
        name: 'Windows ARM64'

      workspace:
        clean: all

      strategy:
        matrix:
          arm64:
            Name: arm64
            Arch: arm64
            Platform: ARM64

      steps:
        - template: ./build-steps-pgo.yml
          parameters:
            PGRun: true

    - job: Build_Python_PGO_3
      displayName: Merge PGO profile
      dependsOn: Build_Python_PGO_2

      pool:
        vmImage: windows-2022

      workspace:
        clean: all

      strategy:
        matrix:
          arm64:
            Name: arm64
            Arch: arm64
            Platform: ARM64
            _HostPython: python

      steps:
        - template: ./build-steps-pgo.yml
          parameters:
            PGUpdate: true


- job: TclTk_Lib
  displayName: Publish Tcl/Tk Library

  pool:
    vmImage: windows-2022

  workspace:
    clean: all

  steps:
  - template: ./checkout.yml

  - script: PCbuild\get_externals.bat --no-openssl --no-libffi
    displayName: 'Get external dependencies'

  - task: MSBuild@1
    displayName: 'Copy Tcl/Tk lib for publish'
    inputs:
      solution: PCbuild\tcltk.props
      platform: x86
      msbuildArguments: /t:CopyTclTkLib /p:OutDir="$(Build.ArtifactStagingDirectory)\tcl_win32"

  - task: MSBuild@1
    displayName: 'Copy Tcl/Tk lib for publish'
    inputs:
      solution: PCbuild\tcltk.props
      platform: x64
      msbuildArguments: /t:CopyTclTkLib /p:OutDir="$(Build.ArtifactStagingDirectory)\tcl_amd64"

  - ${{ if eq(parameters.ARM64TclTk, true) }}:
    - task: MSBuild@1
      displayName: 'Copy Tcl/Tk lib for publish'
      inputs:
        solution: PCbuild\tcltk.props
        platform: ARM64
        msbuildArguments: /t:CopyTclTkLib /p:OutDir="$(Build.ArtifactStagingDirectory)\tcl_arm64"

  - task: PublishPipelineArtifact@0
    displayName: 'Publish artifact: tcltk_lib_win32'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)\tcl_win32'
      artifactName: tcltk_lib_win32

  - task: PublishPipelineArtifact@0
    displayName: 'Publish artifact: tcltk_lib_amd64'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)\tcl_amd64'
      artifactName: tcltk_lib_amd64

  - ${{ if eq(parameters.ARM64TclTk, true) }}:
    - task: PublishPipelineArtifact@0
      displayName: 'Publish artifact: tcltk_lib_arm64'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)\tcl_arm64'
        artifactName: tcltk_lib_arm64
