parameters:
  BuildToPublish: ''
  HashAlgorithms: ['SHA256']
  FeedPath: 'srv/ftp/download/__index_windows__.json'

jobs:
- job: Publish_Python
  displayName: Publish python.org packages
  condition: and(succeeded(), eq(variables['DoMSI'], 'true'), eq(variables['DoEmbed'], 'true'), ne(variables['SkipPythonOrgPublish'], 'true'))

  pool:
    vmImage: windows-2022

  variables:
  - group: PythonOrgPublish

  workspace:
    clean: all

  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.10 or later'
    inputs:
      versionSpec: '>=3.10'

  - ${{ if parameters.BuildToPublish }}:
    - task: DownloadPipelineArtifact@1
      displayName: 'Download artifact from ${{ parameters.BuildToPublish }}: pymanager'
      inputs:
        artifactName: pymanager
        targetPath: $(Build.BinariesDirectory)
        buildType: specific
        project: $(System.TeamProject)
        pipeline: $(Build.DefinitionName)
        buildVersionToDownload: specific
        buildId: ${{ parameters.BuildToPublish }}

  - ${{ else }}:
    - task: DownloadPipelineArtifact@1
      displayName: 'Download artifact: pymanager'
      inputs:
        artifactName: pymanager
        targetPath: $(Build.BinariesDirectory)

  # Note that ARM64 MSIs are skipped at build when this option is specified
  - powershell: 'gci *embed-arm*.zip | %{ Write-Host "Not publishing: $($_.Name)"; gi $_ } | del'
    displayName: 'Prevent publishing ARM64 packages'
    workingDirectory: '$(Build.BinariesDirectory)\pymanager'
    condition: and(succeeded(), ne(variables['PublishARM64'], 'true'))


  - task: DownloadSecureFile@1
    name: sshkey
    inputs:
      secureFile: pydotorg-ssh.ppk
    displayName: 'Download PuTTY key'

  - powershell: |
      "Uploading following files:"
      dir *
      python merge-and-upload.py 
    workingDirectory: $(Build.BinariesDirectory)
    displayName: 'Upload ZIPs'
    env:
      INDEX_PATH: ${{ parameters.FeedPath }}

  - powershell: |
      "Merging following files:"
      dir *.json
      SSH GET ${{ parameters.FeedPath }} __index__.json
      # TODO: Grab current __index__.json
      python -c $env:MERGE_SCRIPT "__index__.json" "*.json"
      # TODO: Upload file
    env:
      MERGE_SCRIPT: |
        import json, glob, hashlib, sys
        
        with open(sys.argv[1], 'rb') as j1:
          j1 = json.load(f1)
        fs = [open(p, 'rb') for glob.glob(sys.argv[2])]
        print("Loaded", len(fs), "files to merge")
        js = [json.load(f) for f in fs]
        [f.close() for f in fs]
        # TODO: Sort?
        for j in js:
            fname = j["url"].rpartition("/")[2]
        j1["versions"][:0] = js
        with open('__index__.json', 'wb') as f1:
          json.dump(f1, j1)
        print("__index__.json now contains", len(j1["versions"]), "entries")

  - ${{ each alg in parameters.HashAlgorithms }}:
    - powershell: |
        $files = gci -File "*.zip"
        $hashes = $files  | `
            Sort-Object Name | `
            Format-Table Name, @{
              Label="${{ alg }}";
              Expression={(Get-FileHash $_ -Algorithm ${{ alg }}).Hash}
            }, Length -AutoSize | `
            Out-String -Width 4096
        $d = mkdir "$(Build.ArtifactStagingDirectory)\hashes" -Force
        $hashes | Out-File "$d\hashes.txt" -Encoding ascii -Append
        $hashes
      workingDirectory: $(Build.BinariesDirectory)
      displayName: 'Generate hashes (${{ alg }})'

  - task: PublishPipelineArtifact@0
    displayName: 'Publish Artifact: hashes'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)\hashes'
      artifactName: hashes
